services:
  billing:
    build: ./billing-service
    ports:
      - "5007:5007"
  inventory:
    build: ./inventory-service
    ports:
      - "5002:5002"
  shipping:
    build: ./shipping-service
    ports:
      - "5009:5009"
  users:
    build: ./users-service
    ports:
      - "5001:5001"